{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.16.aar",
          "url": "ssp-android-0.5.16.aar",
          "size": 354321,
          "sha512": "3b1dbcc77ad68cad483d7b23d5d14bbcce52ccdfd5fa357b26585df9b4496ca428c0465114684cf141c07502e57af98308e1b24be1cddd2160e48e795f6a6e82",
          "sha256": "e4a78486ca5d58dcceab28e40306a9f8ef8b455056c23898f3aea8ffe1cb3116",
          "sha1": "d678b07cc5e13eb930da4efa32e6dc3e47be9e0c",
          "md5": "4f131639378c56a1a08340c0ec471f95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.16.aar",
          "url": "ssp-android-0.5.16.aar",
          "size": 354321,
          "sha512": "3b1dbcc77ad68cad483d7b23d5d14bbcce52ccdfd5fa357b26585df9b4496ca428c0465114684cf141c07502e57af98308e1b24be1cddd2160e48e795f6a6e82",
          "sha256": "e4a78486ca5d58dcceab28e40306a9f8ef8b455056c23898f3aea8ffe1cb3116",
          "sha1": "d678b07cc5e13eb930da4efa32e6dc3e47be9e0c",
          "md5": "4f131639378c56a1a08340c0ec471f95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.16-sources.jar",
          "url": "ssp-android-0.5.16-sources.jar",
          "size": 56517,
          "sha512": "74de5db8bbac317543dcae718d42f961280c5379a9abdfc0a4203a617be253c51fb9f57a8431ab95e1d58ba27ccc425d3d74b8e6e6626ec4ac2b3526b992f252",
          "sha256": "f43da1ffa808ea987cfe6269fc266f2b3e62af3f688ced5dbd7b7a67b60a77d4",
          "sha1": "a9afb20d5e51c7789ece2359447149c5aee8dc47",
          "md5": "1b4052b17a5ff0151ab77e237f10fdd8"
        }
      ]
    }
  ]
}
