{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.20.aar",
          "url": "ssp-android-0.5.20.aar",
          "size": 367481,
          "sha512": "a30c4a8a92487d0c6fb8aad2b36999c332381805247344957ad39a5f435e29cc84379e149c3c7916474f44e7d464819f89629bab9ea6d98643e7a1062285bbf3",
          "sha256": "1ac06b10ab6059acd70d0bb25acdea770b636e7a441dd8036a354530f1559a7e",
          "sha1": "8bbed5dde28440fac42e1e6ba8d9f24ed16e4d4e",
          "md5": "42987a3746c0da242ae91a1e7b59174f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.20.aar",
          "url": "ssp-android-0.5.20.aar",
          "size": 367481,
          "sha512": "a30c4a8a92487d0c6fb8aad2b36999c332381805247344957ad39a5f435e29cc84379e149c3c7916474f44e7d464819f89629bab9ea6d98643e7a1062285bbf3",
          "sha256": "1ac06b10ab6059acd70d0bb25acdea770b636e7a441dd8036a354530f1559a7e",
          "sha1": "8bbed5dde28440fac42e1e6ba8d9f24ed16e4d4e",
          "md5": "42987a3746c0da242ae91a1e7b59174f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.20-sources.jar",
          "url": "ssp-android-0.5.20-sources.jar",
          "size": 60082,
          "sha512": "a4f5868f8152680a52023856fce152601f26661e333fbde0998bca2ea040bfc094a7edb08ba42bbd29e28c20cf8f0539ad9692c89c69a83d8b27991c6263bb24",
          "sha256": "dcf53620557abfbb22e492371f636710ce8a4420e3889c7eba75acc99a38d09f",
          "sha1": "5488fec03fcf519b7ea19b9564184b0386f0ea9d",
          "md5": "f05c95d2ff79d594eb3fb06f05e616a5"
        }
      ]
    }
  ]
}
