{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.3.aar",
          "url": "ssp-android-0.5.3.aar",
          "size": 322512,
          "sha512": "33a4f42130769fa6e09d802fd664bfc04a3d8779878ff4ac0fa2ea03f9086dcd1354292ee4c7a79681dc476ed162826988204d3264e302d8ea56feba14638b69",
          "sha256": "15335fbe6348081f25fe75f4235a8cd178aed77dc94ea1c1d6ae1aa7bde7b63b",
          "sha1": "2f3fe4598023d41ccf80f550c532eaa96e9d6188",
          "md5": "7d12d0fc04ee702c724b0ea53e697a5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.3.aar",
          "url": "ssp-android-0.5.3.aar",
          "size": 322512,
          "sha512": "33a4f42130769fa6e09d802fd664bfc04a3d8779878ff4ac0fa2ea03f9086dcd1354292ee4c7a79681dc476ed162826988204d3264e302d8ea56feba14638b69",
          "sha256": "15335fbe6348081f25fe75f4235a8cd178aed77dc94ea1c1d6ae1aa7bde7b63b",
          "sha1": "2f3fe4598023d41ccf80f550c532eaa96e9d6188",
          "md5": "7d12d0fc04ee702c724b0ea53e697a5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.3-sources.jar",
          "url": "ssp-android-0.5.3-sources.jar",
          "size": 50180,
          "sha512": "dd60a63a6d0257a1b36651b6855552eefe032080317c39cdd67d06c255c4265c6cfbb0ced08096468114fedef98f0a499404233b552c1912e659e892dc42e71d",
          "sha256": "709ac45d1684c28db976d7bb3e8b057af21e7b7797b533e1209e9a0678b55439",
          "sha1": "7f5a09b84996f0ef99862b0d45e7f0452636c345",
          "md5": "38c1ec8ab52fef4aae825d96bcdc1fb5"
        }
      ]
    }
  ]
}
