{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.22.aar",
          "url": "ssp-android-0.5.22.aar",
          "size": 404518,
          "sha512": "5d642127a7a2fffb9dbdd706547f26785d69d4c67739950a9cac8f3062c7d7243b46cd777928ba99701e0153906898c36cf44021f77f3fc09c7a6b85a3c280f6",
          "sha256": "6c2b3629abb04f8cf4cf970c82bc982fe2db29a0e6324c9abdc98cb4c4ad240c",
          "sha1": "a237aadb4b42fb53ff8c571e752829b617fabaf1",
          "md5": "85fb896cb0316045cd8e2974f2614301"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.22.aar",
          "url": "ssp-android-0.5.22.aar",
          "size": 404518,
          "sha512": "5d642127a7a2fffb9dbdd706547f26785d69d4c67739950a9cac8f3062c7d7243b46cd777928ba99701e0153906898c36cf44021f77f3fc09c7a6b85a3c280f6",
          "sha256": "6c2b3629abb04f8cf4cf970c82bc982fe2db29a0e6324c9abdc98cb4c4ad240c",
          "sha1": "a237aadb4b42fb53ff8c571e752829b617fabaf1",
          "md5": "85fb896cb0316045cd8e2974f2614301"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.22-sources.jar",
          "url": "ssp-android-0.5.22-sources.jar",
          "size": 67422,
          "sha512": "ad556208ee151c39f779ad86be4e472025071a4f9c3d3beed880eea20f83a841ecbba44be121396cdbe26db4fde8dff6f09d5742c5ce388187d0976e2cd2677e",
          "sha256": "f82631f51627aed5471c0e9c0027963c4290cbbdbb6f72b643ea9e9181e6b4c9",
          "sha1": "c64d9fc99645cc6dfda00947dd66270012bd849d",
          "md5": "cee0cf3afd559fd8c17a848cc761602d"
        }
      ]
    }
  ]
}
