{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.17.aar",
          "url": "ssp-android-0.5.17.aar",
          "size": 355971,
          "sha512": "1250afcdfd585da562b61f58c1917aa1018fe8a15c8f5f80e4695055f3c1608820d141c75a553328596a31bdfadd6119bb1b21181345aa31cfa082355f93413d",
          "sha256": "6f582743ca33a3555f85560c3c9d023acab3cd1ec8e2a39d5cf0343e968cd5a6",
          "sha1": "428a0452c672dc3e2eae42e599fc562c9832ddea",
          "md5": "48613afa94911d0d50acd2542694bc8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.17.aar",
          "url": "ssp-android-0.5.17.aar",
          "size": 355971,
          "sha512": "1250afcdfd585da562b61f58c1917aa1018fe8a15c8f5f80e4695055f3c1608820d141c75a553328596a31bdfadd6119bb1b21181345aa31cfa082355f93413d",
          "sha256": "6f582743ca33a3555f85560c3c9d023acab3cd1ec8e2a39d5cf0343e968cd5a6",
          "sha1": "428a0452c672dc3e2eae42e599fc562c9832ddea",
          "md5": "48613afa94911d0d50acd2542694bc8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.17-sources.jar",
          "url": "ssp-android-0.5.17-sources.jar",
          "size": 57124,
          "sha512": "e8f248b3fd11a95a23231e613bd0bb44a7e5e0dd2c012a44466f03de1980835c6ca1ead23bd530b5f486eaec9ded861885eb180b37d0a1ae5fadbf69ec62bff6",
          "sha256": "6b32790268aa4a7e1c0fe0ca8fbdb474edfd1e5353ac2f0dcf29fe3a571d352f",
          "sha1": "adffcf012d0817baeda904dda18f9f5f03c14d69",
          "md5": "0ee0fdee738cbfb28832e22d8535a282"
        }
      ]
    }
  ]
}
