{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.23.aar",
          "url": "ssp-android-0.5.23.aar",
          "size": 414992,
          "sha512": "5f355ab39c58033328e48fb54ce5815f5bda14eb5077f2e77696924ed4d162188622b3cecaecb494ee2be9c45f348d239462c1abf0bbcb4822a8cc71c0b6331c",
          "sha256": "bf9ca757e70d8d41e794dd2fdab4eddaa6396450219d89b2d24a0dd3b2a2788a",
          "sha1": "a04544ba45854dbc02f41581bc69b59ef30f0913",
          "md5": "acc0ccc3b1da9877d4442215f4628e38"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.23.aar",
          "url": "ssp-android-0.5.23.aar",
          "size": 414992,
          "sha512": "5f355ab39c58033328e48fb54ce5815f5bda14eb5077f2e77696924ed4d162188622b3cecaecb494ee2be9c45f348d239462c1abf0bbcb4822a8cc71c0b6331c",
          "sha256": "bf9ca757e70d8d41e794dd2fdab4eddaa6396450219d89b2d24a0dd3b2a2788a",
          "sha1": "a04544ba45854dbc02f41581bc69b59ef30f0913",
          "md5": "acc0ccc3b1da9877d4442215f4628e38"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.23-sources.jar",
          "url": "ssp-android-0.5.23-sources.jar",
          "size": 70790,
          "sha512": "ca73cc904786555be1444f9174dfab594c3ca9dd7ff64d007ee54161d6b640cafa7f60825bc10be43f3305b2ac7d2909bbc03b75b36d3e14b10337793185ddb0",
          "sha256": "56a8bc54abe06bdc5eecdb1e4b168b80d75968e919dc8e09b50cfd109f9bb77e",
          "sha1": "7dfa750ce32b9f2d1c245ddecb9226e454d7c3fa",
          "md5": "285e54c91b60a488c93b5b372b6b1e48"
        }
      ]
    }
  ]
}
