{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.9.aar",
          "url": "ssp-android-0.5.9.aar",
          "size": 330618,
          "sha512": "b42936d41023bb7d524bc230424335062d7cbb1b0b2b2960b370ee5098b23d7ec965d2d7ef70260fb049dde6491da7a811b0a55cf51cfbb71b9dbc214ce74d3d",
          "sha256": "30b1f8046ad1f718ac65fa627710a5c567e6e88253420890a514c57fab6acb58",
          "sha1": "a044ac768508cc4168fc66720ede6ec987756afb",
          "md5": "9f6b6e76c56bedf4c74ccee279f3ddda"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.9.aar",
          "url": "ssp-android-0.5.9.aar",
          "size": 330618,
          "sha512": "b42936d41023bb7d524bc230424335062d7cbb1b0b2b2960b370ee5098b23d7ec965d2d7ef70260fb049dde6491da7a811b0a55cf51cfbb71b9dbc214ce74d3d",
          "sha256": "30b1f8046ad1f718ac65fa627710a5c567e6e88253420890a514c57fab6acb58",
          "sha1": "a044ac768508cc4168fc66720ede6ec987756afb",
          "md5": "9f6b6e76c56bedf4c74ccee279f3ddda"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.9-sources.jar",
          "url": "ssp-android-0.5.9-sources.jar",
          "size": 52150,
          "sha512": "2374820ec54b0ec90dd310842c6053b625577db80a4387269502f6e1a447572f681644f15b466269e9299e639b42659242667109450134c7ee26e6ab66279022",
          "sha256": "6c1918877b0a828ea35da79d68922aae91f58c954c056696f507ea126db689e7",
          "sha1": "b156ee7f4c5b696d53a65a9bbcfeb35a466c3d03",
          "md5": "a1af5b64fcf37d6a573a3b1ada446598"
        }
      ]
    }
  ]
}
