{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.7.aar",
          "url": "ssp-android-0.5.7.aar",
          "size": 330619,
          "sha512": "6c9455e541243d0366a0e6d92b9c11e474e57b3363861e795af9a67c1c2e8ed2e7c021b8168445c87129f184a1bda43f75852a0b8c20eb53a62352fc6161f34f",
          "sha256": "1da044afe745a4500956d7bbbbf7704965e45e3985f2511fb4272cf6c1099fef",
          "sha1": "d64eebf49d93918b6ea839706902182ccc6b34ba",
          "md5": "654162a75f5ad41b50851df13c06dba9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.7.aar",
          "url": "ssp-android-0.5.7.aar",
          "size": 330619,
          "sha512": "6c9455e541243d0366a0e6d92b9c11e474e57b3363861e795af9a67c1c2e8ed2e7c021b8168445c87129f184a1bda43f75852a0b8c20eb53a62352fc6161f34f",
          "sha256": "1da044afe745a4500956d7bbbbf7704965e45e3985f2511fb4272cf6c1099fef",
          "sha1": "d64eebf49d93918b6ea839706902182ccc6b34ba",
          "md5": "654162a75f5ad41b50851df13c06dba9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.7-sources.jar",
          "url": "ssp-android-0.5.7-sources.jar",
          "size": 52150,
          "sha512": "d6c9fcdf6273d942f3df713e17ef62431d24bb92f39f8a9c80921953f8ffd82eb806e5622598216ae7eaf6296847abf505c947d966dc7e37d1110b8a5b5e1bf4",
          "sha256": "7acd5193b8e582700a681010e1be3ecbe92454738a8b4dea900a95560f66e974",
          "sha1": "a17937bd80e1b5e9c7ac1a189f24a2e4b0d65e3c",
          "md5": "8649d833f1b8032b3d473fdb64616f46"
        }
      ]
    }
  ]
}
