{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.25.aar",
          "url": "ssp-android-0.5.25.aar",
          "size": 432825,
          "sha512": "d87b9973b819ea5e02d602711b2a9d73a00753e8a8c78d901b599b5aa1ba1afa3a2cdf11ef2b7a2fcabe1868d4cb5f9f0ca74c9f8ae35286e392a0322c50d8fa",
          "sha256": "0677851c3b45998d73b4a4333e1966e09577775554822cc0b8a18bd90de071d5",
          "sha1": "a842919fa8962bb635ec21c8a5e209672c6eae3f",
          "md5": "d283d1e0dc9cd0976f09cdd74bf31dc6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.25.aar",
          "url": "ssp-android-0.5.25.aar",
          "size": 432825,
          "sha512": "d87b9973b819ea5e02d602711b2a9d73a00753e8a8c78d901b599b5aa1ba1afa3a2cdf11ef2b7a2fcabe1868d4cb5f9f0ca74c9f8ae35286e392a0322c50d8fa",
          "sha256": "0677851c3b45998d73b4a4333e1966e09577775554822cc0b8a18bd90de071d5",
          "sha1": "a842919fa8962bb635ec21c8a5e209672c6eae3f",
          "md5": "d283d1e0dc9cd0976f09cdd74bf31dc6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.25-sources.jar",
          "url": "ssp-android-0.5.25-sources.jar",
          "size": 73395,
          "sha512": "30861cfe3e91c8b2a226c54e1a933a2b11197d3b89f75ae49aa99c0b540c60f9ff583e6d598024922ca632eec024c0ad5b7eed204108f970e9590af3405c76cc",
          "sha256": "398db1f1852cc29e2abb10a4bf2e1a4db2271c5ead67f455c4d97e985a900f46",
          "sha1": "a876baa4c99fbb7ced522cccd7aa041f5e57e3bf",
          "md5": "d7e491f572527ed1b2905b46c0dea157"
        }
      ]
    }
  ]
}
