{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.10.aar",
          "url": "ssp-android-0.5.10.aar",
          "size": 330622,
          "sha512": "77ac73655805a447fb35962377a8574a25e3bd39c3bc1b16dcc185f36696c1a7a104e64e7ce7f22f8730fcdaa7295a02dd608a3a8e9fcb29798fd472e9a61491",
          "sha256": "cc9b806278e2557cea4c07c74ff8e104299bc4f5ddf419655f8f48553388332b",
          "sha1": "7ba7bb0897046ce2e3abe1be5dada071c389f758",
          "md5": "a8198b2f873e21f239612a0cb2f9949c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.10.aar",
          "url": "ssp-android-0.5.10.aar",
          "size": 330622,
          "sha512": "77ac73655805a447fb35962377a8574a25e3bd39c3bc1b16dcc185f36696c1a7a104e64e7ce7f22f8730fcdaa7295a02dd608a3a8e9fcb29798fd472e9a61491",
          "sha256": "cc9b806278e2557cea4c07c74ff8e104299bc4f5ddf419655f8f48553388332b",
          "sha1": "7ba7bb0897046ce2e3abe1be5dada071c389f758",
          "md5": "a8198b2f873e21f239612a0cb2f9949c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.10-sources.jar",
          "url": "ssp-android-0.5.10-sources.jar",
          "size": 52151,
          "sha512": "e90549cccd8499623dba34f4b4e384d66ca0942840a7473a5f5c8b47080c7f62a9f72100954ab5fbaccd0d22358423fabdd1c5ea92687e9c5f9e63f8d65b2993",
          "sha256": "3052a133ab8a534589fc040f350b9319a7636cf7e1cb0d4688fc90f13e56e23b",
          "sha1": "bcf4396f2f981f05f31fe2c2d7aefb31125f16a6",
          "md5": "43018ec8fd24023d759eb63e1eba9738"
        }
      ]
    }
  ]
}
