{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.21.aar",
          "url": "ssp-android-0.5.21.aar",
          "size": 367650,
          "sha512": "64ceb25702f1969b59411300b4ae8ffad9b459ef4f88ee9c9ac84ad663629e6868695abd2341eec80f8887ea9a9b5dc2fa382449578f14cd920195a34f502fd1",
          "sha256": "273001bc7734b82fe87132cb8e2b6ddb3cacdd936b6d18019fa4c877e57d38a8",
          "sha1": "2f4fa37f97081945248258148ea88be96cc16b0e",
          "md5": "982aa670bdc5b466b62fb4dd8f16ed87"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.21.aar",
          "url": "ssp-android-0.5.21.aar",
          "size": 367650,
          "sha512": "64ceb25702f1969b59411300b4ae8ffad9b459ef4f88ee9c9ac84ad663629e6868695abd2341eec80f8887ea9a9b5dc2fa382449578f14cd920195a34f502fd1",
          "sha256": "273001bc7734b82fe87132cb8e2b6ddb3cacdd936b6d18019fa4c877e57d38a8",
          "sha1": "2f4fa37f97081945248258148ea88be96cc16b0e",
          "md5": "982aa670bdc5b466b62fb4dd8f16ed87"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.21-sources.jar",
          "url": "ssp-android-0.5.21-sources.jar",
          "size": 60204,
          "sha512": "69312e20fd851e43d1a00ee2dbcae300f46d470139a71067a30bc3c67224504edf823dcbc37c71f4d6db8af25d25be84e0fa58dfc8ca24adb4a825d63f8e5891",
          "sha256": "d213738b1dcf7fee691db4f1170d9a4ce16fd9465a33a0b0013c5eb8406f4c0a",
          "sha1": "faf4f194e99083772f33ef6de9b6441937ffa849",
          "md5": "655f443f6fe799b3ed282e65f3940d6a"
        }
      ]
    }
  ]
}
