{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dkmads.ssp",
    "module": "ssp-android",
    "version": "0.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.2.aar",
          "url": "ssp-android-0.5.2.aar",
          "size": 322518,
          "sha512": "9a3c77f26021c806c4759187d8ff4a51c5ff95c46be89b87b7d60cf69aca2b3f319dd0cd41439a729b8bd15abc3b111e6fe98cd27f6b3362815d71cf0ea08e25",
          "sha256": "93d269e3d5ce914bbf510b4ff71fbc1334c9a59aaadf6ae3762269554ef90b7f",
          "sha1": "26d141dd6f08cb1a865ca6c9fe0d07939a9ce2bb",
          "md5": "3e87f700412b6114aac9cf62e00d1e81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "ssp-android-0.5.2.aar",
          "url": "ssp-android-0.5.2.aar",
          "size": 322518,
          "sha512": "9a3c77f26021c806c4759187d8ff4a51c5ff95c46be89b87b7d60cf69aca2b3f319dd0cd41439a729b8bd15abc3b111e6fe98cd27f6b3362815d71cf0ea08e25",
          "sha256": "93d269e3d5ce914bbf510b4ff71fbc1334c9a59aaadf6ae3762269554ef90b7f",
          "sha1": "26d141dd6f08cb1a865ca6c9fe0d07939a9ce2bb",
          "md5": "3e87f700412b6114aac9cf62e00d1e81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ssp-android-0.5.2-sources.jar",
          "url": "ssp-android-0.5.2-sources.jar",
          "size": 50180,
          "sha512": "586e0fff79402c028f82b6386252fd42fb15ae6d4bdd176b6baf6e74f76223e57ac5d0dc81ea4314dfe4953c8dd1d7fd7cf8ff91a4af41298af62d7cbf310e8f",
          "sha256": "80b37a0dac6c001ce40ed2ac6fee74b99133db672e82e26ac1b55e6aacfbb36f",
          "sha1": "58c2071ce362a7b6f0f1121437b9e9d4f95a9b95",
          "md5": "1abc9f72f243682f46d6a17d03ee40f1"
        }
      ]
    }
  ]
}
